### ISSUE TITLE
How to expose rmb in the helm chart

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/tfgridclient_proxy#111]
It's relatively easy to do tcp forwarding using nginx, but this will allow only one rmb per cluster. Another option is to investigate how to make nginx serve http over multiple ports including 80.  From [here](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/controller-service.yaml#L52) it looks like only one port is possible (from helm args like `values.yaml` or `--set`) but maybe there's another way to do it. Another option is to fork the repo and modify the service definition to include additional ports.

**Comment by OmarElawady** [comment]
The nginx chart values can be modified to expose over tcp. With the rmb service added here https://github.com/threefoldtech/tfgridclient_proxy/pull/112

```yaml
tcp:
    8051: default/gridproxy-rmb:8051
controller:
    nodePorts:
      tcp:
        8051: 8051
```
